### ISSUE TITLE
customnpc scripts don't work with graalvm enterprise edition

### ISSUE THREAD

**Issue by JustCursed** [KAMKEEL/CustomNPC-Plus#100]
**Issue description:**
if i start a server using graalvm enterprise edition, all the scripts stop working

**for example:**
* event: damaged
* script: `npc.say(event.getDamage());`
* result:
```
Sun Jul 16 16:12:05 MSK 2023 tab 5:
javax.script.ScriptException: org.graalvm.polyglot.PolyglotException: TypeError: invokeMember (getDamage) on noppes.npcs.scripted.event.ScriptEventDamaged@4c2da842 failed due to: Unknown identifier: getDamage
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.toScriptException(GraalJSScriptEngine.java:483)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:460)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.access$400(GraalJSScriptEngine.java:83)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine$10.eval(GraalJSScriptEngine.java:628)
	at noppes.npcs.controllers.ScriptContainer.run(ScriptContainer.java:98)
	at noppes.npcs.DataScript.callScript(DataScript.java:142)
	at noppes.npcs.DataScript.callScript(DataScript.java:128)
	at noppes.npcs.EventHooks.onNPCDamaged(EventHooks.java:169)
	at noppes.npcs.entity.EntityNPCInterface.func_70097_a(EntityNPCInterface.java:508)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1399)
	at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1622)
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55)
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:990)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:808)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:683)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.graalvm.polyglot.PolyglotException: TypeError: invokeMember (getDamage) on noppes.npcs.scripted.event.ScriptEventDamaged@4c2da842 failed due to: Unknown identifier: getDamage
	at <js>.:program(<eval>:1)
	at org.graalvm.polyglot.Context.eval(Context.java:379)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:458)
	... 18 more
```

**Versions:**
* Minecraft: 1.7.10 and 1.12.2 (i haven't tried others)
* Forge: 
* CustomNPC+: latest from curseforge (1.8.6), but i think, it actually for all versions cnpc

**Comment by KAMKEEL** [comment]
Sorry, but there are a lot of uncertainties with GraalVM and CustomNPC+. We currently support Nashorn.
