### ISSUE TITLE
Invalid signature exception on launch

### ISSUE THREAD

**Issue by slit-bodmod** [KAMKEEL/CustomNPC-Plus#103]
hey I just cloned the project according to the instructions on the GitHub readme.
however immediately after starting I hit runClient and get an exception that reads:
Caused by: java.lang.SecurityException: Invalid signature file digest for Manifest main attributes

the output reads like this:

`18:41:11: Executing 'runClient'...

Found AccessTransformer in main resources: customnpcs_at.cfg
Path: /Users/jacobmaynardvesely/IdeaProjects/CustomNPCplus
:compileApiJavaNote: SpongePowered MIXIN Annotation Processor Version=0.7.11
Note: ObfuscationServiceMCP supports type: "searge"
Note: ObfuscationServiceMCP supports type: "notch"
Note: /Users/jacobmaynardvesely/IdeaProjects/CustomNPCplus/src/api/java/net/minecraft/util/math/IntHashMap.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

:processApiResources NO-SOURCE
:apiClasses
:sourceMainJava
:compileJavaNote: SpongePowered MIXIN Annotation Processor Version=0.8
Note: ObfuscationServiceMCP supports type: "searge"
Note: ObfuscationServiceMCP supports type: "notch"
Note: Loading searge mappings from /Users/jacobmaynardvesely/.gradle/caches/minecraft/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/srgs/mcp-srg.srg
Note: Writing refmap to /Users/jacobmaynardvesely/IdeaProjects/CustomNPCplus/build/tmp/compileJava/customnpcs.refmap.json
Note: Writing refmap to /Users/jacobmaynardvesely/IdeaProjects/CustomNPCplus/build/tmp/compileJava/customnpcs.refmap.json
Note: Writing searge output SRGs to /Users/jacobmaynardvesely/IdeaProjects/CustomNPCplus/build/tmp/reobf/mixins.srg
Note: Writing refmap to /Users/jacobmaynardvesely/IdeaProjects/CustomNPCplus/build/tmp/compileJava/customnpcs.refmap.json
Note: Writing refmap to /Users/jacobmaynardvesely/IdeaProjects/CustomNPCplus/build/tmp/compileJava/customnpcs.refmap.json
Note: Writing searge output SRGs to /Users/jacobmaynardvesely/IdeaProjects/CustomNPCplus/build/tmp/reobf/mixins.srg
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

:processResources
:classes
:jar
:getVersionJsonIndex UP-TO-DATE
:getVersionJson UP-TO-DATE
:extractUserDev UP-TO-DATE
:extractNatives UP-TO-DATE
:getAssetsIndex UP-TO-DATE
:getAssets UP-TO-DATE
:makeStart SKIPPED
:runClient
[18:43:40] [main/INFO] [GradleStart]: Extra: []
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.searchCoremods(Unknown Source)
	at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
	at GradleStart.main(Unknown Source)
Caused by: java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:330)
	at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:263)
	at java.util.jar.JarVerifier.processEntry(JarVerifier.java:275)
	at java.util.jar.JarVerifier.update(JarVerifier.java:230)
	at java.util.jar.JarFile.initializeVerifier(JarFile.java:383)
	at java.util.jar.JarFile.getInputStream(JarFile.java:450)
	at cpw.mods.fml.common.asm.transformers.ModAccessTransformer$JarByteSource.openStream(ModAccessTransformer.java:69)
	at com.google.common.io.ByteSource$AsCharSource.openStream(ByteSource.java:435)
	at com.google.common.io.CharSource.read(CharSource.java:162)
	at cpw.mods.fml.common.asm.transformers.ModAccessTransformer.addJar(ModAccessTransformer.java:52)
	... 6 more
:runClient FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runClient'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 28s
12 actionable tasks: 6 executed, 6 up-to-date
18:43:41: Execution finished 'runClient'.`

**Comment by slit-bodmod** [comment]
hmm ok, now I am getting this error: 
`Exception in thread "main" java.lang.UnsatisfiedLinkError: no lwjgl in java.library.path`
