### ISSUE TITLE
Mage staff

### ISSUE THREAD

**Issue by zxterProxy** [KAMKEEL/CustomNPC-Plus#4]
* CustomNPC-Plus-1.1**
* Minecraft: 1.7.10
* Forge: 
* CustomNPC+: 

strange bug. when using the magic staff, the mage crashes *

MODS 
 mcp - Minecraft Coder Pack - 9.05
 FML - Forge Mod Loader - 7.10.99.99
 Forge - Minecraft Forge - 10.13.4.1614
 kimagine - KImagine - 0.2
 ColorUtility - ColorUtility - 1.0.3
 CodeChickenCore - CodeChicken Core - 1.0.7.48
 NotEnoughItems - Not Enough Items - 1.0.5.120
 Enchiridion - Enchiridion - 1.3
 Enchiridion2 - Enchiridion 2 - 2.0.2a
 BiomesOPlenty - Biomes O' Plenty - 2.1.0
 customnpcs - CustomNpcs - 1.1
 discordintegration - DiscordIntegration - 3.0.4
 Baubles - Baubles - 1.0.1.10
 Thaumcraft - Thaumcraft - 4.2.3.5
 etfuturum - Et Futurum Requiem - 2.1.3
 Morpheus - Morpheus - 1.7.10-1.6.21
 profilehandler - Profile Handler - 1.0
 rpi - Role-playing-items - 0.1
 skinport - SkinPort - 1.7.10-v10d
 soulsconverter - soulsconverter - 1.4-fix
 soulscore - SoulsCore - 1.6
 trade - Trade - 1.0.1
 EventHelper - EventHelper - 1.7.10-1.13
 attackdelay - Ariamis attack delay mod - Minecraft 1.7.10
 ariamis - Ariamis expansion - 0.2
 MineTweaker3 - MineTweaker 3 - 3.0.13
 minefantasy2 - MineFantasyII - 2.8.14.8
 mfhealthbar - mfhealthbar - 0.9.4
 bookshelf_chest - BookshelfChest - 1.0
 campfirebackport - Campfire Backport - ${version}
 CarpentersBlocks - Carpenter's Blocks - 3.3.8.2_fix
 examplemod - Example Mod - 1.0
 damagetilt - Damage Tilt - 0.1.0
 doorsoplenty - Doors o Plenty - 0.1
 Emotes - Emotes - 1.0
 GardenContainers - Garden Containers - 1.7.10-1.7.0
 GardenCore - Garden Core - 1.7.10-1.7.0
 GardenStuff - Garden Stuff - 1.7.10-1.7.0
 GardenTrees - Garden Trees - 1.7.10-1.7.0
 MCP_Wheel - MC+ Wheel - 1.1.2
 MCP_Cart - MC+ Cart - 1.3.0
 MCP_WoodenBucket - MC+ WoodenBucket - 1.2.0
 MTRM - MineTweakerRecipeMaker - 1.0
 modtweaker2 - Mod Tweaker 2 - 0.9.6
 ariamisportal - Ariamis Portal - 0.7.3
 tcinventoryscan - TC Inventory Scanning - 1.0.11
 ta - ThaumcraftAriamis - 1.0
 thaumcraftneiplugin - Thaumcraft NEI Plugin - @VERSION@
 thaumicdyes - Thaumic Dyes - 1.10.1
 infernalskycolor - Infernal Sky Color - 0.8
 plonk - Plonk - 1.7.10-0.0.7
 wizardry - Electroblob's Wizardry - 1.1.5
 netherlicious - ?6Netherlicious - 2.7.1
 antiqueatlas - Antique Atlas - 4.4.0
 betterstorage - BetterStorage - 0.13.1.128
 signposts - Sign-Posts - 1.2.1
 climatecontrol - Climate Control - 0.8.1
 RTG - Realistic Terrain Generation - 1.7.10-1.1.1.7
 bspkrsCore - bspkrsCore - 6.16

**Comment by zxterProxy** [comment]
[22:16:20] [Client thread/ERROR] [FML]: A severe problem occurred during the spawning of an entity at ( 6.625,16.09375, 303.375)
java.lang.NoSuchMethodException: noppes.npcs.entity.EntityMagicProjectile.<init>(net.minecraft.world.World)
	at java.lang.Class.getConstructor0(Class.java:3082) ~[?:1.8.0_231]
	at java.lang.Class.getConstructor(Class.java:1825) ~[?:1.8.0_231]
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.spawnEntity(EntitySpawnHandler.java:77) [EntitySpawnHandler.class:?]
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.channelRead0(EntitySpawnHandler.java:34) [EntitySpawnHandler.class:?]
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.channelRead0(EntitySpawnHandler.java:28) [EntitySpawnHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_231]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12-launcherfixed.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12-launcherfixed.jar:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627) [?:1.8.0_231]
	at pro.gravit.launcher.client.ClientLauncherEntryPoint.launch(ClientLauncherEntryPoint.java:266) [Launcher.exe:?]
	at pro.gravit.launcher.client.ClientLauncherEntryPoint.main(ClientLauncherEntryPoint.java:163) [Launcher.exe:?]
[22:16:20] [Client thread/ERROR] [FML]: EntitySpawnHandler exception
java.lang.RuntimeException: java.lang.NoSuchMethodException: noppes.npcs.entity.EntityMagicProjectile.<init>(net.minecraft.world.World)
	at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[guava-16.0.jar:?]
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.spawnEntity(EntitySpawnHandler.java:126) ~[EntitySpawnHandler.class:?]
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.channelRead0(EntitySpawnHandler.java:34) ~[EntitySpawnHandler.class:?]
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.channelRead0(EntitySpawnHandler.java:28) ~[EntitySpawnHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_231]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12-launcherfixed.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12-launcherfixed.jar:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627) [?:1.8.0_231]
	at pro.gravit.launcher.client.ClientLauncherEntryPoint.launch(ClientLauncherEntryPoint.java:266) [Launcher.exe:?]
	at pro.gravit.launcher.client.ClientLauncherEntryPoint.main(ClientLauncherEntryPoint.java:163) [Launcher.exe:?]
Caused by: java.lang.NoSuchMethodException: noppes.npcs.entity.EntityMagicProjectile.<init>(net.minecraft.world.World)
	at java.lang.Class.getConstructor0(Class.java:3082) ~[?:1.8.0_231]
	at java.lang.Class.getConstructor(Class.java:1825) ~[?:1.8.0_231]
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.spawnEntity(EntitySpawnHandler.java:77) ~[EntitySpawnHandler.class:?]
	... 27 more
[22:16:20] [Client thread/ERROR] [FML]: OpenGuiHandler exception
java.lang.RuntimeException: java.lang.NoSuchMethodException: noppes.npcs.entity.EntityMagicProjectile.<init>(net.minecraft.world.World)
	at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[guava-16.0.jar:?]
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.spawnEntity(EntitySpawnHandler.java:126) ~[EntitySpawnHandler.class:?]
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.channelRead0(EntitySpawnHandler.java:34) ~[EntitySpawnHandler.class:?]
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.channelRead0(EntitySpawnHandler.java:28) ~[EntitySpawnHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_231]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12-launcherfixed.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12-launcherfixed.jar:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627) [?:1.8.0_231]
	at pro.gravit.launcher.client.ClientLauncherEntryPoint.launch(ClientLauncherEntryPoint.java:266) [Launcher.exe:?]
	at pro.gravit.launcher.client.ClientLauncherEntryPoint.main(ClientLauncherEntryPoint.java:163) [Launcher.exe:?]
Caused by: java.lang.NoSuchMethodException: noppes.npcs.entity.EntityMagicProjectile.<init>(net.minecraft.world.World)
	at java.lang.Class.getConstructor0(Class.java:3082) ~[?:1.8.0_231]
	at java.lang.Class.getConstructor(Class.java:1825) ~[?:1.8.0_231]
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.spawnEntity(EntitySpawnHandler.java:77) ~[EntitySpawnHandler.class:?]
	... 27 more
[22:16:20] [Client thread/ERROR] [FML]: HandshakeCompletionHandler exception
java.lang.RuntimeException: java.lang.NoSuchMethodException: noppes.npcs.entity.EntityMagicProjectile.<init>(net.minecraft.world.World)
	at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[guava-16.0.jar:?]
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.spawnEntity(EntitySpawnHandler.java:126) ~[EntitySpawnHandler.class:?]
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.channelRead0(EntitySpawnHandler.java:34) ~[EntitySpawnHandler.class:?]
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.channelRead0(EntitySpawnHandler.java:28) ~[EntitySpawnHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_231]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12-launcherfixed.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12-launcherfixed.jar:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627) [?:1.8.0_231]
	at pro.gravit.launcher.client.ClientLauncherEntryPoint.launch(ClientLauncherEntryPoint.java:266) [Launcher.exe:?]
	at pro.gravit.launcher.client.ClientLauncherEntryPoint.main(ClientLauncherEntryPoint.java:163) [Launcher.exe:?]
Caused by: java.lang.NoSuchMethodException: noppes.npcs.entity.EntityMagicProjectile.<init>(net.minecraft.world.World)
	at java.lang.Class.getConstructor0(Class.java:3082) ~[?:1.8.0_231]
	at java.lang.Class.getConstructor(Class.java:1825) ~[?:1.8.0_231]
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.spawnEntity(EntitySpawnHandler.java:77) ~[EntitySpawnHandler.class:?]
	... 27 more
[22:16:20] [Client thread/ERROR] [FML]: There was a critical exception handling a packet on channel FML
java.lang.RuntimeException: java.lang.NoSuchMethodException: noppes.npcs.entity.EntityMagicProjectile.<init>(net.minecraft.world.World)
	at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[guava-16.0.jar:?]
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.spawnEntity(EntitySpawnHandler.java:126) ~[EntitySpawnHandler.class:?]
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.channelRead0(EntitySpawnHandler.java:34) ~[EntitySpawnHandler.class:?]
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.channelRead0(EntitySpawnHandler.java:28) ~[EntitySpawnHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_231]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12-launcherfixed.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12-launcherfixed.jar:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627) [?:1.8.0_231]
	at pro.gravit.launcher.client.ClientLauncherEntryPoint.launch(ClientLauncherEntryPoint.java:266) [Launcher.exe:?]
	at pro.gravit.launcher.client.ClientLauncherEntryPoint.main(ClientLauncherEntryPoint.java:163) [Launcher.exe:?]
Caused by: java.lang.NoSuchMethodException: noppes.npcs.entity.EntityMagicProjectile.<init>(net.minecraft.world.World)
	at java.lang.Class.getConstructor0(Class.java:3082) ~[?:1.8.0_231]
	at java.lang.Class.getConstructor(Class.java:1825) ~[?:1.8.0_231]
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.spawnEntity(EntitySpawnHandler.java:77) ~[EntitySpawnHandler.class:?]
	... 27 more
[22:16:20] [Netty Client IO #15/INFO] [THAUMCRAFT]: Restoring client configs.
[22:16:20] [Client thread/INFO] [FML]: Applying holder lookups
[22:16:20] [Client thread/INFO] [FML]: Holder lookups applied

**Comment by zxterProxy** [comment]
This error occurs both on the server and in the single player game. I've already seen this in old versions of the original mod *

**Comment by zxterProxy** [comment]
![image](https://user-images.githubusercontent.com/47256412/119557420-d7f14200-bda8-11eb-9fbe-cba302e2ed8f.png)
Also, skins by nickname are not displayed

**Comment by zxterProxy** [comment]
![image](https://user-images.githubusercontent.com/47256412/119557516-f5bea700-bda8-11eb-9946-315b41b0852d.png)
This is the standard skin in my resource pack

**Comment by zxterProxy** [comment]
I tried using Custom NPC-Plus-1.1.
In this case, I got not just a crash but a crash when using the staff. Friend I very much respect your work but your mod is notably broken. Take more responsibility for your work, because I can put it on my minecraft server.
[crash-2021-05-25_22.55.34-server.txt](https://github.com/KAMKEEL/CustomNPC-Plus/files/6542014/crash-2021-05-25_22.55.34-server.txt)

**Comment by KAMKEEL** [comment]
Hello Zxter,

Can you please explain the issue regarding the the nicknames not being displayed? I have corrected the Staff Issue and it will be in the latest release. I am taking responsibility, like most mods, errors will always be found and adjusted for as I intend to do.

**Comment by KAMKEEL** [comment]
Please Open another Issue regarding that Nickname issue and I will address it there, but seeing that the Staff Bug will be fixed in the next release, I will be closing this.
